source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Apodidae_Example' do
  pod "Apodidae", :path => "../"
end

target 'Apodidae_Tests' do
  pod "Apodidae", :path => "../"

  pod 'Quick', '~> 1.1.0'
  pod 'Nimble', '6.0.1'
end
